export default [
    ` `,
    `#############################################################################################`,
    `#                                                                                           #`,
    `#<color="yellow">                               _                                                           </color>#`,
    `#<color="yellow">                              (_)                                                          </color>#`,
    `#<color="yellow">         _ __ ___  _ __  _ __  _  ___ _ __  _   _ _ __   ___   ___ ___  _ __ ___           </color>#`,
    `#<color="yellow">        | '__/ _ \\| '_ \\| '_ \\| |/ _ \\ '_ \\| | | | '_ \\ / _ \\ / __/ _ \\| '_ \` _ \\          </color>#`,
    `#<color="yellow">        | | | (_) | | | | | | | |  __/ |_) | |_| | | | |  __/| (_| (_) | | | | | |         </color>#`,
    `#<color="yellow">        |_|  \\___/|_| |_|_| |_|_|\\___| .__/ \\__, |_| |_|\\___</color><color="white">(_)</color><color="yellow">___\\___/|_| |_| |_|         </color>#`,
    `#<color="yellow">                                     | |    __/ /                                          </color>#`,
    `#<color="yellow">                                     |_|   |___/                                           </color>#`,
    `#                                                                                           #`,
    `#                                 -------------------------                                 #`,
    `#                                                                                           #`,
    `#            Hi, I'm <color="yellow">Ronnie Pyne</color> - Web Software Developer in Sydney, Australia              #`,
    `#                      Please type <color="yellow">menu</color> for a full list of commands.                        #`,
    `#                                                                                           #`,
    `#                                                                                           #`,
    `#############################################################################################`,
    ` `
]
