language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "bko5x/zB6MM/qxBZgZUyvpl+LQJZ2NtcRMyi8Sv5SM3XpFacjJvUlWpt8PxwOA3LEVddSAmqAe6fdgL2+UfPsiP7pdBS/oYej1Vu4xEEeMndRzhfqhWm/MI9csSDlmGlWoULN3HuyeXHJmSZWxEoggMWvJWxAgc4i8cf7DrIZdWPV70LmHVhOu5NaWhgICzyJFAF7eq/LKmdjW/oy+vTpTUzOCyA2uPcpoVqHH5IHInMUngSUOlCVRU9ftSgj1vBSt1vmOE31XgZlofkXOZ7kul7kYirxiKfUmsvYKBT6sfnANRAbI4C+6zYXpz+W09tuwr4jsC2KZzNFV7tl6o3FOJ4HG4VpSkW9z14IpsQWnmNYKFp4A9PUGevtby9Ku4glFsMkKtKcXOf28XHdndo3BzaIBOJEQL0/ZfHSdjKa0K8ivHsOUX1l35hibUbqOShoQGyW6dRw7Wu7VonMH7fufMIaUihOlmhLplqGcJkrTKnEB7FJvg1KYRC1QvimM4fa05I/HnAnCl7KsZPKfpM/t8wuwZ6eGCe0L7zQI2AV0DkZPsh0WMlOWFHcW+juBLVWo9MInkp1VxcIFt5IPu/v6doXaGH6STlDimIuzjjk5Z+MxzyjwP01Iczg7GE/BMk6Hpi7Ht5Afsl4gCIcMpqYuB4SGuSkVfZIVq6BAt1gLo="
  app: rp-vue-terminal-homepage