runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /dist
  static_dir: dist/

skip_files:
  - ^node_modules/.*?
